services:
  crossjobs-community:
    container_name: crossjobs-community
    image: ghcr.io/justicea83/crossjobs-community:latest
    expose:
      - "9000"
    volumes:
      - ./community/storage:/var/www/html/storage

  crossjobs-community-nginx:
    container_name:  crossjobs-community-nginx
    image: ghcr.io/justicea83/crossjobs-community-nginx:latest
    depends_on:
      - crossjobs-community
    ports:
      - "6204:80"
