name: Build and Push docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      IMAGE_NAME: crossjobs-community
      REPOSITORY: taskflow-community
      GH_USERNAME: justicea83
      APP_ROOT: ghcr.io/justicea83

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables for VM credentials
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # setup the environment variable for production
            echo "CURRENT_ENV=prod" >> $GITHUB_ENV

            echo "VM_HOST=${{ secrets.VM_HOST_PROD }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}" >> $GITHUB_ENV
            echo "DB_DATABASE=${{ secrets.DB_DATABASE_PROD }}" >> $GITHUB_ENV
            echo "DB_USERNAME=${{ secrets.DB_USERNAME_PROD }}" >> $GITHUB_ENV
          fi

      - name: Create .env file
        run: |
          echo "${{ vars.ENV_PROD }}" > .env
          cat .env  # Optional: Display the contents for debugging (remove in production)
          ls -la


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GH_USERNAME --password-stdin

      - name: Clear VM Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          username: justicea83
          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
          script: |
            cd /home/justicea83
            rm -rf docker-compose.c.${{ env.CURRENT_ENV }}.api.yml

      - name: Transfer docker-compose to VM
        run: |
          # Write the SSH private key to a temporary file
          if [[ "${{ env.CURRENT_ENV }}" == "dev" ]]; then
            echo "${{ secrets.VM_SSH_SECRET_DEV }}" > ssh_key
          elif [[ "${{ env.CURRENT_ENV }}" == "prod" ]]; then
            echo "${{ secrets.VM_SSH_SECRET_PROD }}" > ssh_key
          fi

          chmod 600 ssh_key

          # Use the temporary file for SCP
          scp -o StrictHostKeyChecking=no -i ssh_key docker-compose.c.${{ env.CURRENT_ENV }}.api.static.yml justicea83@${{ env.VM_HOST }}:/home/justicea83

          scp -o StrictHostKeyChecking=no -i ssh_key docker-compose.c.${{ env.CURRENT_ENV }}.api.yml justicea83@${{ env.VM_HOST }}:/home/justicea83

          # Clean up by removing the temporary SSH key file
          rm -f ssh_key

      - name: Build and Push Image
        run: |
          echo "building ane push"
          docker build . -t $APP_ROOT/$IMAGE_NAME:$IMAGE_TAG
          docker push $APP_ROOT/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          command_timeout: 200m
          username: justicea83
          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
          script: |
            cd /home/justicea83

            DB_USERNAME="${{ env.DB_USERNAME }}" DB_DATABASE="${{ env.DB_DATABASE }}" DB_PASSWORD="${{ env.DB_PASSWORD }}" docker compose -f docker-compose.c.${{ env.CURRENT_ENV }}.api.static.yml up -d

            if [ $( docker ps -a | grep ${{ env.IMAGE_NAME }} | wc -l ) -gt 0 ]; then
               docker compose -f docker-compose.c.${{ env.CURRENT_ENV }}.api.yml pull
            fi

            docker compose -f docker-compose.c.${{ env.CURRENT_ENV }}.api.yml up -d --build

            docker image prune -a -f
